export const FABRIC_CATEGORIES = [
  { name: 'Lawn', slug: 'lawn', description: 'Lightweight printed and embroidered lawn for spring and summer.' },
  { name: 'Khaddar', slug: 'khaddar', description: 'Warm, textured khaddar for cooler days and winter layering.' },
  { name: 'Linen', slug: 'linen', description: 'Premium linen with a refined drape for autumn and winter.' },
  { name: 'Viscose', slug: 'viscose', description: 'Soft, flowing viscose for everyday and semi-formal wear.' },
  { name: 'Cotton', slug: 'cotton', description: 'Comfortable everyday cotton for effortless daily dressing.' },
  { name: 'Chiffon', slug: 'chiffon', description: 'Airy chiffon, primarily for elegant dupattas and dressier looks.' },
  { name: 'Silk', slug: 'silk', description: 'Lustrous silk for premium and occasion-ready collections.' },
  { name: 'Organza', slug: 'organza', description: 'Crisp organza for formal dupattas and evening ensembles.' },
] as const;

export const PIECE_TYPES = [
  { key: '1-piece', label: '1 Piece', included: ['Shirt'] },
  { key: '2-piece', label: '2 Piece', included: ['Shirt', 'Trouser'] },
  { key: '3-piece', label: '3 Piece', included: ['Shirt', 'Trouser', 'Dupatta'] },
  { key: 'dupatta', label: 'Dupatta', included: ['Dupatta'] },
] as const;

export type PieceTypeKey = (typeof PIECE_TYPES)[number]['key'];

export type UnstitchedProduct = {
  name: string;
  slug: string;
  fabric: string;
  pieceType: PieceTypeKey;
  color: string;
  collection: string;
  pattern: string;
  embroidery: string;
  season: string;
  priceCents: number;
  compareAtCents?: number;
  stock: number;
  featured?: boolean;
  description: string;
  fabricInfo: string;
  images: string[];
};

const essa = (...ids: number[]) =>
  ids.map((id) => `/uploads/essa/img-${String(id).padStart(2, '0')}.jpg`);

const LINEN_INFO = 'Printed linen with a refined autumn–winter drape, sold unstitched.';
const KHADDAR_INFO = 'Printed khaddar with a warm, textured hand for cooler days.';
const COTTON_INFO = 'Printed cambric cotton with a comfortable everyday weight.';

export const UNSTITCHED_PRODUCTS: UnstitchedProduct[] = [
  {
    name: 'Noor-e-Sabz Linen 3 Piece',
    slug: 'noor-e-sabz-linen-3-piece',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Sage Green',
    collection: 'Linen Atelier',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 549500,
    stock: 22,
    featured: true,
    description:
      'A worn linen lookbook ensemble in sage green, styled as an unstitched three-piece with a printed shirt, coordinated trouser and matching dupatta.',
    fabricInfo: LINEN_INFO,
    images: essa(1),
  },
  {
    name: 'Gulnaar Magenta Linen',
    slug: 'gulnaar-magenta-linen',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Magenta',
    collection: 'Linen Atelier',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 549500,
    stock: 18,
    featured: true,
    description:
      'A vivid magenta linen three-piece photographed on the figure — printed shirt, trouser and a coordinated dupatta for winter gatherings.',
    fabricInfo: LINEN_INFO,
    images: essa(2),
  },
  {
    name: 'Meher Sand Linen Ensemble',
    slug: 'meher-sand-linen-ensemble',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Sand',
    collection: 'Linen Atelier',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 549500,
    stock: 20,
    description:
      'Warm sand-toned linen cut as an unstitched three-piece, with a softly printed shirt paired with a matching trouser and dupatta.',
    fabricInfo: LINEN_INFO,
    images: essa(3),
  },
  {
    name: 'Zareen Ivory & Gold Linen',
    slug: 'zareen-ivory-gold-linen',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Ivory',
    collection: 'Linen Atelier',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 549500,
    stock: 16,
    description:
      'Ivory linen with gold-toned print detail, styled as a three-piece shirt, trouser and dupatta for a quieter winter look.',
    fabricInfo: LINEN_INFO,
    images: essa(4),
  },
  {
    name: 'Aabroo Navy Linen 3 Piece',
    slug: 'aabroo-navy-linen-3-piece',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Navy',
    collection: 'Linen Atelier',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 549500,
    stock: 19,
    featured: true,
    description:
      'Deep navy linen photographed as a worn three-piece — printed shirt, trouser and a coordinated dupatta with a formal winter drape.',
    fabricInfo: LINEN_INFO,
    images: essa(5),
  },
  {
    name: 'Mahveen Dusty Rose Linen',
    slug: 'mahveen-dusty-rose-linen',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Dusty Rose',
    collection: 'Linen Atelier',
    pattern: 'Floral Print',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 549500,
    stock: 21,
    description:
      'A dusty-rose linen three-piece with a soft floral shirt print, matching trouser and a lightly coordinated dupatta.',
    fabricInfo: LINEN_INFO,
    images: essa(6),
  },
  {
    name: 'Shabnam Black & Pink Linen',
    slug: 'shabnam-black-pink-linen',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Black',
    collection: 'Linen Atelier',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 549500,
    stock: 15,
    description:
      'Black linen with pink print accents, presented as an unstitched three-piece shirt, trouser and dupatta.',
    fabricInfo: LINEN_INFO,
    images: essa(7),
  },
  {
    name: 'Roshni Maroon Linen 3 Piece',
    slug: 'roshni-maroon-linen-3-piece',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Deep Maroon',
    collection: 'Linen Atelier',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 549500,
    stock: 17,
    featured: true,
    description:
      'A maroon linen three-piece with a worn, editorial presentation — printed shirt, trouser and matching dupatta in Essa’s winter palette.',
    fabricInfo: LINEN_INFO,
    images: essa(8),
  },
  {
    name: 'Safa Aqua Linen 3 Piece',
    slug: 'safa-aqua-linen-3-piece',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Aqua',
    collection: 'Linen Atelier',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 549000,
    stock: 24,
    featured: true,
    description:
      'Cool aqua linen styled on the figure as a three-piece — printed shirt, trouser and a coordinated dupatta.',
    fabricInfo: LINEN_INFO,
    images: essa(9),
  },
  {
    name: 'Anjum Crimson Linen',
    slug: 'anjum-crimson-linen',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Crimson',
    collection: 'Linen Atelier',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 549000,
    stock: 18,
    description:
      'A crimson linen three-piece with a printed shirt, matching trouser and dupatta for a bolder winter colour story.',
    fabricInfo: LINEN_INFO,
    images: essa(10),
  },
  {
    name: 'Dastaan Cocoa Floral Linen',
    slug: 'dastaan-cocoa-floral-linen',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Cocoa',
    collection: 'Linen Atelier',
    pattern: 'Floral Print',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 549000,
    stock: 16,
    description:
      'Cocoa-brown linen with a floral print, cut as an unstitched shirt, trouser and dupatta.',
    fabricInfo: LINEN_INFO,
    images: essa(11),
  },
  {
    name: 'Laleh Hot Pink Linen',
    slug: 'laleh-hot-pink-linen',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Hot Pink',
    collection: 'Linen Atelier',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 549500,
    stock: 14,
    description:
      'Hot-pink linen presented as a three-piece ensemble with a printed shirt, trouser and coordinated dupatta.',
    fabricInfo: LINEN_INFO,
    images: essa(12),
  },
  {
    name: 'Yasmin Mint Linen 3 Piece',
    slug: 'yasmin-mint-linen-3-piece',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Mint',
    collection: 'Linen Atelier',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 549000,
    stock: 20,
    description:
      'Mint linen with a fresh printed shirt, matching trouser and a lightly coordinated dupatta.',
    fabricInfo: LINEN_INFO,
    images: essa(13),
  },
  {
    name: 'Sitara Sunshine Linen',
    slug: 'sitara-sunshine-linen',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Yellow',
    collection: 'Linen Atelier',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 549000,
    stock: 19,
    description:
      'A sunlit yellow linen three-piece — printed shirt, trouser and dupatta for a brighter winter wardrobe.',
    fabricInfo: LINEN_INFO,
    images: essa(14),
  },
  {
    name: 'Haya Black Border Linen',
    slug: 'haya-black-border-linen',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Black',
    collection: 'Linen Atelier',
    pattern: 'Bordered',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 549000,
    stock: 15,
    description:
      'Black linen with a pink border story, sold as an unstitched three-piece shirt, trouser and dupatta.',
    fabricInfo: LINEN_INFO,
    images: essa(15),
  },
  {
    name: 'Gulshan Peach Linen',
    slug: 'gulshan-peach-linen',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Peach',
    collection: 'Linen Atelier',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 549000,
    stock: 22,
    description:
      'Soft peach linen styled as a three-piece with a printed shirt, trouser and matching dupatta.',
    fabricInfo: LINEN_INFO,
    images: essa(16),
  },
  {
    name: 'Rang-e-Chaman Linen 3 Piece',
    slug: 'rang-e-chaman-linen-3-piece',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Green',
    collection: 'Linen Atelier',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 549000,
    stock: 18,
    description:
      'Green linen with a yellow-toned dupatta contrast, presented as an unstitched shirt, trouser and dupatta set.',
    fabricInfo: LINEN_INFO,
    images: essa(17),
  },
  {
    name: 'Noor-e-Aasman Ikat Linen',
    slug: 'noor-e-aasman-ikat-linen',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Blue',
    collection: 'Linen Atelier',
    pattern: 'Ikat Print',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 549000,
    stock: 17,
    featured: true,
    description:
      'Blue ikat-inspired linen photographed as a worn three-piece — shirt, trouser and a coordinated dupatta.',
    fabricInfo: LINEN_INFO,
    images: essa(18),
  },
  {
    name: 'Mehrunisa Pink & Blue Linen',
    slug: 'mehrunisa-pink-blue-linen',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Pink',
    collection: 'Linen Atelier',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 549000,
    stock: 21,
    description:
      'A pink-and-blue linen three-piece with a printed shirt, matching trouser and coordinated dupatta.',
    fabricInfo: LINEN_INFO,
    images: essa(19),
  },
  {
    name: 'Firdaus Purple Winter 3 Piece',
    slug: 'firdaus-purple-winter-3-piece',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Purple',
    collection: 'Winter Edit',
    pattern: 'Floral Print',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 629000,
    stock: 14,
    description:
      'A purple floral winter three-piece shown as a flat lay — printed shirt with coordinated trouser and dupatta.',
    fabricInfo: LINEN_INFO,
    images: essa(20),
  },
  {
    name: 'Zeenat Forest Print',
    slug: 'zeenat-forest-print',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Forest Green',
    collection: 'Winter Edit',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 649000,
    stock: 13,
    description:
      'Forest-green winter cloth with a zebra-like print, laid out as an unstitched shirt, trouser and dupatta.',
    fabricInfo: LINEN_INFO,
    images: essa(21),
  },
  {
    name: 'Banafsha Lilac Winter',
    slug: 'banafsha-lilac-winter',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Lilac',
    collection: 'Winter Edit',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 619000,
    stock: 15,
    description:
      'Lilac winter three-piece with a printed shirt, matching trouser and a coordinated dupatta in a soft flat-lay.',
    fabricInfo: LINEN_INFO,
    images: essa(22),
  },
  {
    name: 'Nargis Sage Ikat',
    slug: 'nargis-sage-ikat',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Sage Green',
    collection: 'Winter Edit',
    pattern: 'Ikat Print',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 639000,
    stock: 12,
    description:
      'Sage ikat winter cloth arranged as a three-piece — printed shirt, trouser and dupatta.',
    fabricInfo: LINEN_INFO,
    images: essa(23),
  },
  {
    name: 'Amber Mustard Winter',
    slug: 'amber-mustard-winter',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Mustard',
    collection: 'Winter Edit',
    pattern: 'Floral Print',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 629000,
    stock: 14,
    description:
      'Mustard floral winter three-piece shown as a coordinated shirt, trouser and dupatta flat lay.',
    fabricInfo: LINEN_INFO,
    images: essa(24),
  },
  {
    name: 'Shab-e-Gul Black Floral',
    slug: 'shab-e-gul-black-floral',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Black',
    collection: 'Winter Edit',
    pattern: 'Floral Print',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 649000,
    stock: 11,
    description:
      'Black floral winter cloth laid as an unstitched three-piece shirt, trouser and dupatta.',
    fabricInfo: LINEN_INFO,
    images: essa(25),
  },
  {
    name: 'Nilofar Periwinkle 3 Piece',
    slug: 'nilofar-periwinkle-3-piece',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Periwinkle',
    collection: 'Winter Edit',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 619000,
    stock: 16,
    description:
      'Periwinkle winter three-piece with a printed shirt, matching trouser and coordinated dupatta.',
    fabricInfo: LINEN_INFO,
    images: essa(26),
  },
  {
    name: 'Samandar Navy Dots',
    slug: 'samandar-navy-dots',
    fabric: 'linen',
    pieceType: '3-piece',
    color: 'Navy',
    collection: 'Winter Edit',
    pattern: 'Dotted',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 599000,
    stock: 17,
    description:
      'Navy dotted winter cloth presented as a three-piece shirt, trouser and dupatta.',
    fabricInfo: LINEN_INFO,
    images: essa(27),
  },
  {
    name: 'Laal Khaddar 3 Piece',
    slug: 'laal-khaddar-3-piece',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Red',
    collection: 'Winter Khaddar',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 499000,
    stock: 20,
    description:
      'A stacked red khaddar three-piece — printed shirt with coordinated trouser and dupatta for winter wear.',
    fabricInfo: KHADDAR_INFO,
    images: essa(28),
  },
  {
    name: 'Jamuni Floral Khaddar 3 Piece',
    slug: 'jamuni-floral-khaddar-3-piece',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Black',
    collection: 'Winter Khaddar',
    pattern: 'Floral Print',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 499000,
    stock: 18,
    description:
      'Black-and-purple floral khaddar stacked as a three-piece shirt, trouser and dupatta.',
    fabricInfo: KHADDAR_INFO,
    images: essa(29),
  },
  {
    name: 'Sehar Peach Cotton 3 Piece',
    slug: 'sehar-peach-cotton-3-piece',
    fabric: 'cotton',
    pieceType: '3-piece',
    color: 'Peach',
    collection: 'Everyday Cotton',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'All Season',
    priceCents: 399000,
    stock: 26,
    description:
      'Peach cambric cotton stacked as an unstitched three-piece — shirt, trouser and dupatta for everyday wear.',
    fabricInfo: COTTON_INFO,
    images: essa(30),
  },
  {
    name: 'Afsana Stripe Khaddar',
    slug: 'afsana-stripe-khaddar',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Orange',
    collection: 'Winter Khaddar',
    pattern: 'Striped',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 529000,
    stock: 16,
    featured: true,
    description:
      'Orange-and-olive striped khaddar shown both styled and stacked — an unstitched three-piece shirt, trouser and dupatta.',
    fabricInfo: KHADDAR_INFO,
    images: essa(48, 31),
  },
  {
    name: 'Gulbahar Maroon Khaddar',
    slug: 'gulbahar-maroon-khaddar',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Deep Maroon',
    collection: 'Winter Khaddar',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 519000,
    stock: 18,
    description:
      'Maroon-and-green printed khaddar arranged as a three-piece shirt, trouser and dupatta.',
    fabricInfo: KHADDAR_INFO,
    images: essa(32),
  },
  {
    name: 'Meher Pink Paisley Khaddar',
    slug: 'meher-pink-paisley-khaddar',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Pink',
    collection: 'Winter Khaddar',
    pattern: 'Paisley',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 499000,
    stock: 19,
    description:
      'Pink paisley khaddar sold as an unstitched three-piece with shirt, trouser and matching dupatta.',
    fabricInfo: KHADDAR_INFO,
    images: essa(33),
  },
  {
    name: 'Zoya Dark Paisley',
    slug: 'zoya-dark-paisley',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Charcoal',
    collection: 'Winter Khaddar',
    pattern: 'Paisley',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 509000,
    stock: 15,
    description:
      'A darker paisley khaddar three-piece — printed shirt, trouser and coordinated dupatta.',
    fabricInfo: KHADDAR_INFO,
    images: essa(34),
  },
  {
    name: 'Inara Teal Khaddar',
    slug: 'inara-teal-khaddar',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Teal',
    collection: 'Winter Khaddar',
    pattern: 'Floral Print',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 499000,
    stock: 17,
    description:
      'Teal floral khaddar presented as a three-piece shirt, trouser and dupatta.',
    fabricInfo: KHADDAR_INFO,
    images: essa(35),
  },
  {
    name: 'Layan Purple Leaf Khaddar',
    slug: 'layan-purple-leaf-khaddar',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Purple',
    collection: 'Winter Khaddar',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 489000,
    stock: 18,
    description:
      'Purple leaf-print khaddar cut as an unstitched shirt, trouser and dupatta.',
    fabricInfo: KHADDAR_INFO,
    images: essa(36),
  },
  {
    name: 'Nisa Beige Dots 3 Piece',
    slug: 'nisa-beige-dots-3-piece',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Beige',
    collection: 'Winter Khaddar',
    pattern: 'Dotted',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 479000,
    stock: 20,
    description:
      'Beige dotted khaddar arranged as a three-piece — printed shirt, trouser and dupatta.',
    fabricInfo: KHADDAR_INFO,
    images: essa(37),
  },
  {
    name: 'Kainat Black Floral Khaddar',
    slug: 'kainat-black-floral-khaddar',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Black',
    collection: 'Winter Khaddar',
    pattern: 'Floral Print',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 509000,
    stock: 14,
    description:
      'Black floral khaddar sold as a three-piece shirt, trouser and coordinated dupatta.',
    fabricInfo: KHADDAR_INFO,
    images: essa(38),
  },
  {
    name: 'Aabroo Maroon & Beige Khaddar',
    slug: 'aabroo-maroon-beige-khaddar',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Deep Maroon',
    collection: 'Winter Khaddar',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 519000,
    stock: 16,
    description:
      'Maroon-and-beige printed khaddar presented as an unstitched three-piece ensemble.',
    fabricInfo: KHADDAR_INFO,
    images: essa(39),
  },
  {
    name: 'Samina Navy Aqua Khaddar',
    slug: 'samina-navy-aqua-khaddar',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Navy',
    collection: 'Winter Khaddar',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 499000,
    stock: 17,
    description:
      'Navy-and-aqua printed khaddar cut as a shirt, trouser and matching dupatta.',
    fabricInfo: KHADDAR_INFO,
    images: essa(40),
  },
  {
    name: 'Shabnam Ice Blue Khaddar',
    slug: 'shabnam-ice-blue-khaddar',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Ice Blue',
    collection: 'Winter Khaddar',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 489000,
    stock: 19,
    description:
      'Ice-blue printed khaddar arranged as a three-piece shirt, trouser and dupatta.',
    fabricInfo: KHADDAR_INFO,
    images: essa(41),
  },
  {
    name: 'Gulnaar Magenta Khaddar',
    slug: 'gulnaar-magenta-khaddar',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Magenta',
    collection: 'Winter Khaddar',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 499000,
    stock: 15,
    description:
      'Magenta printed khaddar sold as an unstitched three-piece for winter.',
    fabricInfo: KHADDAR_INFO,
    images: essa(42),
  },
  {
    name: 'Rehan Navy Geo Khaddar',
    slug: 'rehan-navy-geo-khaddar',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Navy',
    collection: 'Winter Khaddar',
    pattern: 'Geometric',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 509000,
    stock: 16,
    description:
      'Navy geometric khaddar presented as a three-piece shirt, trouser and dupatta.',
    fabricInfo: KHADDAR_INFO,
    images: essa(43),
  },
  {
    name: 'Zarmina Mustard Paisley',
    slug: 'zarmina-mustard-paisley',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Mustard',
    collection: 'Winter Khaddar',
    pattern: 'Paisley',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 519000,
    stock: 14,
    description:
      'Mustard-and-black paisley khaddar cut as an unstitched shirt, trouser and dupatta.',
    fabricInfo: KHADDAR_INFO,
    images: essa(44),
  },
  {
    name: 'Bano Lilac Zigzag',
    slug: 'bano-lilac-zigzag',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Lilac',
    collection: 'Winter Khaddar',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 479000,
    stock: 18,
    description:
      'Lilac zigzag-print khaddar arranged as a three-piece ensemble.',
    fabricInfo: KHADDAR_INFO,
    images: essa(45),
  },
  {
    name: 'Amber Mustard 2 Piece',
    slug: 'amber-mustard-2-piece',
    fabric: 'khaddar',
    pieceType: '2-piece',
    color: 'Mustard',
    collection: 'Khaddar Two Piece',
    pattern: 'Floral Print',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 399000,
    stock: 22,
    description:
      'Mustard floral khaddar sold as a two-piece shirt and trouser — no dupatta included.',
    fabricInfo: KHADDAR_INFO,
    images: essa(46),
  },
  {
    name: 'Jamun Plum 2 Piece',
    slug: 'jamun-plum-2-piece',
    fabric: 'khaddar',
    pieceType: '2-piece',
    color: 'Plum',
    collection: 'Khaddar Two Piece',
    pattern: 'Printed',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 379000,
    stock: 20,
    description:
      'Plum printed khaddar cut as an unstitched shirt-and-trouser pairing.',
    fabricInfo: KHADDAR_INFO,
    images: essa(47),
  },
  {
    name: 'Alina Navy Stripe 2 Piece',
    slug: 'alina-navy-stripe-2-piece',
    fabric: 'khaddar',
    pieceType: '2-piece',
    color: 'Navy',
    collection: 'Khaddar Two Piece',
    pattern: 'Striped',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 389000,
    stock: 21,
    description:
      'Navy diamond-stripe khaddar presented as a two-piece shirt and trouser.',
    fabricInfo: KHADDAR_INFO,
    images: essa(49),
  },
  {
    name: 'Laal Gul 2 Piece',
    slug: 'laal-gul-2-piece',
    fabric: 'khaddar',
    pieceType: '2-piece',
    color: 'Deep Maroon',
    collection: 'Khaddar Two Piece',
    pattern: 'Floral Print',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 399000,
    stock: 19,
    description:
      'Maroon floral khaddar sold as an unstitched two-piece shirt and trouser.',
    fabricInfo: KHADDAR_INFO,
    images: essa(50),
  },
  {
    name: 'Nisa Beige Dots 2 Piece',
    slug: 'nisa-beige-dots-2-piece',
    fabric: 'khaddar',
    pieceType: '2-piece',
    color: 'Beige',
    collection: 'Khaddar Two Piece',
    pattern: 'Dotted',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 369000,
    stock: 23,
    description:
      'Beige dotted khaddar as a two-piece — printed shirt with a coordinated trouser.',
    fabricInfo: KHADDAR_INFO,
    images: essa(51),
  },
  {
    name: 'Jamuni Floral 2 Piece',
    slug: 'jamuni-floral-2-piece',
    fabric: 'khaddar',
    pieceType: '2-piece',
    color: 'Black',
    collection: 'Khaddar Two Piece',
    pattern: 'Floral Print',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 389000,
    stock: 18,
    description:
      'Black-and-purple floral khaddar cut as a two-piece shirt and trouser.',
    fabricInfo: KHADDAR_INFO,
    images: essa(52),
  },
  {
    name: 'Sehar Cream Botanical',
    slug: 'sehar-cream-botanical',
    fabric: 'khaddar',
    pieceType: '2-piece',
    color: 'Cream',
    collection: 'Khaddar Two Piece',
    pattern: 'Floral Print',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 379000,
    stock: 20,
    description:
      'Cream botanical khaddar presented as an unstitched shirt-and-trouser set.',
    fabricInfo: KHADDAR_INFO,
    images: essa(53),
  },
  {
    name: 'Dastaan Chocolate Geo 2 Piece',
    slug: 'dastaan-chocolate-geo-2-piece',
    fabric: 'khaddar',
    pieceType: '2-piece',
    color: 'Chocolate',
    collection: 'Khaddar Two Piece',
    pattern: 'Geometric',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 399000,
    stock: 17,
    description:
      'Chocolate geometric khaddar sold as a two-piece shirt and trouser.',
    fabricInfo: KHADDAR_INFO,
    images: essa(54),
  },
  {
    name: 'Roshni Maroon Paisley 2 Piece',
    slug: 'roshni-maroon-paisley-2-piece',
    fabric: 'khaddar',
    pieceType: '2-piece',
    color: 'Deep Maroon',
    collection: 'Khaddar Two Piece',
    pattern: 'Paisley',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 359000,
    stock: 24,
    description:
      'Maroon khaddar with scattered paisley motifs, folded as a two-piece shirt and trouser.',
    fabricInfo: KHADDAR_INFO,
    images: essa(55),
  },
  {
    name: 'Sitara Stripe Khaddar 3 Piece',
    slug: 'sitara-stripe-khaddar-3-piece',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Ivory',
    collection: 'Winter Khaddar',
    pattern: 'Striped',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 479000,
    stock: 18,
    description:
      'Ivory-and-black striped khaddar with teal and green borders, stacked as a three-piece shirt, trouser and dupatta.',
    fabricInfo: KHADDAR_INFO,
    images: essa(56),
  },
  {
    name: 'Noor Navy Vine Khaddar',
    slug: 'noor-navy-vine-khaddar',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Navy',
    collection: 'Winter Khaddar',
    pattern: 'Floral Print',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 489000,
    stock: 16,
    description:
      'Navy khaddar with a pale vine print, presented as an unstitched three-piece.',
    fabricInfo: KHADDAR_INFO,
    images: essa(57),
  },
  {
    name: 'Mehrunisa Maroon Geo 3 Piece',
    slug: 'mehrunisa-maroon-geo-3-piece',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Deep Maroon',
    collection: 'Winter Khaddar',
    pattern: 'Geometric',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 499000,
    stock: 17,
    description:
      'Maroon geometric khaddar stacked as a three-piece shirt, trouser and dupatta.',
    fabricInfo: KHADDAR_INFO,
    images: essa(58),
  },
  {
    name: 'Alina Navy Khaddar 3 Piece',
    slug: 'alina-navy-khaddar-3-piece',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Navy',
    collection: 'Winter Khaddar',
    pattern: 'Striped',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 499000,
    stock: 15,
    description:
      'Navy dotted-stripe khaddar with a patterned border piece, sold as a three-piece ensemble.',
    fabricInfo: KHADDAR_INFO,
    images: essa(59),
  },
  {
    name: 'Firdaus Plum Vine 3 Piece',
    slug: 'firdaus-plum-vine-3-piece',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Plum',
    collection: 'Winter Khaddar',
    pattern: 'Floral Print',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 489000,
    stock: 16,
    description:
      'Plum khaddar with a pale vine print — printed shirt, dyed trouser and printed dupatta.',
    fabricInfo: KHADDAR_INFO,
    images: essa(60),
  },
  {
    name: 'Anjum Maroon Navy 2 Piece',
    slug: 'anjum-maroon-navy-2-piece',
    fabric: 'khaddar',
    pieceType: '2-piece',
    color: 'Deep Maroon',
    collection: 'Khaddar Two Piece',
    pattern: 'Floral Print',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 369000,
    stock: 22,
    description:
      'Maroon floral khaddar paired with a navy piece, sold as a two-piece shirt and trouser.',
    fabricInfo: KHADDAR_INFO,
    images: essa(61),
  },
  {
    name: 'Banafsha Purple Vine 3 Piece',
    slug: 'banafsha-purple-vine-3-piece',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Purple',
    collection: 'Winter Khaddar',
    pattern: 'Floral Print',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 499000,
    stock: 18,
    description:
      'Purple vine-print khaddar stacked as three matching printed pieces — shirt, trouser and dupatta.',
    fabricInfo: KHADDAR_INFO,
    images: essa(62),
  },
  {
    name: 'Samandar Navy 2 Piece',
    slug: 'samandar-navy-2-piece',
    fabric: 'khaddar',
    pieceType: '2-piece',
    color: 'Navy',
    collection: 'Khaddar Two Piece',
    pattern: 'Striped',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 389000,
    stock: 20,
    description:
      'Navy dotted-stripe khaddar with a solid navy trouser, sold as an unstitched two-piece.',
    fabricInfo: KHADDAR_INFO,
    images: essa(63),
  },
  {
    name: 'Gulshan Rose Khaddar 3 Piece',
    slug: 'gulshan-rose-khaddar-3-piece',
    fabric: 'khaddar',
    pieceType: '3-piece',
    color: 'Rose',
    collection: 'Winter Khaddar',
    pattern: 'Floral Print',
    embroidery: 'None',
    season: 'Winter',
    priceCents: 479000,
    stock: 19,
    description:
      'Rose floral khaddar with a dyed trouser — printed shirt, plain trouser and printed dupatta.',
    fabricInfo: KHADDAR_INFO,
    images: essa(64),
  },
  {
    name: 'Inara Teal Cotton 3 Piece',
    slug: 'inara-teal-cotton-3-piece',
    fabric: 'cotton',
    pieceType: '3-piece',
    color: 'Teal',
    collection: 'Everyday Cotton',
    pattern: 'Floral Print',
    embroidery: 'None',
    season: 'All Season',
    priceCents: 429000,
    stock: 24,
    description:
      'Teal floral cambric cotton stacked as a three-piece shirt, trouser and dupatta.',
    fabricInfo: COTTON_INFO,
    images: essa(65),
  },
];

export const HERO_IMAGES = {
  featured: { src: '/uploads/essa/img-08.jpg', alt: 'Roshni maroon linen three-piece' },
  supportA: { src: '/uploads/essa/img-02.jpg', alt: 'Gulnaar magenta linen' },
  supportB: { src: '/uploads/essa/img-05.jpg', alt: 'Aabroo navy linen three-piece' },
};

export function pieceTypeMeta(key: PieceTypeKey) {
  return PIECE_TYPES.find((p) => p.key === key) || PIECE_TYPES[2];
}

export function colorSlug(color: string) {
  return color.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

export function productTags(p: UnstitchedProduct) {
  const tags = [
    p.fabric,
    p.pieceType,
    colorSlug(p.color),
    p.pattern.toLowerCase().replace(/\s+/g, '-'),
    p.season.toLowerCase().replace(/\s+/g, '-'),
    'unstitched',
    'women',
  ];
  if (p.embroidery && p.embroidery !== 'None') tags.push('embroidered');
  if (p.featured) tags.push('featured');
  if (p.pieceType === 'dupatta') tags.push('dupattas');
  return [...new Set(tags)];
}

export function searchTagHints(q: string) {
  const n = q.toLowerCase().trim();
  const tags: string[] = [];
  if (/\b3[\s-]?piece\b/.test(n)) tags.push('3-piece');
  if (/\b2[\s-]?piece\b/.test(n)) tags.push('2-piece');
  if (/\b1[\s-]?piece\b/.test(n)) tags.push('1-piece');
  if (/\bdupatta/.test(n)) tags.push('dupatta', 'dupattas');
  for (const fabric of FABRIC_CATEGORIES) {
    if (n.includes(fabric.slug)) tags.push(fabric.slug);
  }
  if (n.includes('embroider')) tags.push('embroidered');
  if (n.includes('print')) tags.push('printed');
  if (n.includes('unstitched')) tags.push('unstitched');
  const colorish = n.replace(/[^a-z0-9\s-]/g, '').trim();
  if (colorish) tags.push(colorish.replace(/\s+/g, '-'));
  return [...new Set(tags)];
}
